"""add_users_and_properties

Revision ID: 5bb9d83748f6
Revises: d5f2a3b4c601
Create Date: 2026-04-09 10:39:56.382946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb9d83748f6'
down_revision: Union[str, None] = 'd5f2a3b4c601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('situacao', sa.String(length=100), nullable=True),
    sa.Column('finalidade', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('suites', sa.Integer(), nullable=True),
    sa.Column('banheiros', sa.Integer(), nullable=True),
    sa.Column('vagas', sa.Integer(), nullable=True),
    sa.Column('andar', sa.Integer(), nullable=True),
    sa.Column('total_andares', sa.Integer(), nullable=True),
    sa.Column('elevadores', sa.Integer(), nullable=True),
    sa.Column('unidades_andar', sa.Integer(), nullable=True),
    sa.Column('area_privativa', sa.Float(), nullable=True),
    sa.Column('area_total', sa.Float(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('condominio', sa.Float(), nullable=True),
    sa.Column('iptu', sa.Float(), nullable=True),
    sa.Column('diferenciais', sa.String(length=500), nullable=True),
    sa.Column('acabamento', sa.String(length=500), nullable=True),
    sa.Column('empreendimento', sa.String(length=500), nullable=True),
    sa.Column('construtora', sa.String(length=500), nullable=True),
    sa.Column('entrega', sa.String(length=20), nullable=True),
    sa.Column('fotos_url', sa.Text(), nullable=True),
    sa.Column('tour_360', sa.Text(), nullable=True),
    sa.Column('planta_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('corretor_responsavel', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('aceita_permuta', sa.Boolean(), nullable=False),
    sa.Column('aceita_financiamento', sa.Boolean(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('lancamento', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_bairro'), 'properties', ['bairro'], unique=False)
    op.create_index(op.f('ix_properties_codigo'), 'properties', ['codigo'], unique=True)
    op.create_index(op.f('ix_properties_disponivel'), 'properties', ['disponivel'], unique=False)
    op.create_index(op.f('ix_properties_lancamento'), 'properties', ['lancamento'], unique=False)
    op.create_index(op.f('ix_properties_valor'), 'properties', ['valor'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_properties_valor'), table_name='properties')
    op.drop_index(op.f('ix_properties_lancamento'), table_name='properties')
    op.drop_index(op.f('ix_properties_disponivel'), table_name='properties')
    op.drop_index(op.f('ix_properties_codigo'), table_name='properties')
    op.drop_index(op.f('ix_properties_bairro'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
